name: 'Build and Push docker image'

on:
  push:
    branches:
      - 'master'
      
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest 
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: steevi
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: read environment file
        run: cat .env >>${GITHUB_ENV}          
      
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: steevi/caddy-cloudflare:${{ env.caddy_version }}
          build-args: |
            VERSION=${{ env.caddy_version }}
