name: 'Build and Scan docker image'

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest 
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: steevi
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: read environment file
        run: cat .env >>${GITHUB_ENV}          
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: steevi/caddy-cloudflare:${{ env.caddy_version }}
          build-args: |
            VERSION=${{ env.caddy_version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'steevi/caddy-cloudflare:${{ env.caddy_version }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
