name: 'Build on Master'

on:
  push:
    branches: [ master ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest 
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: steevi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image
        run:  source source.rc && docker build --build-arg VERSION=${CADDY_VERSION} -t steevi/caddy-cloudflare:${CADDY_VERSION} . && docker push steevi/caddy-cloudflare:${CADDY_VERSION}