name: 'Build and Scan docker image'

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest 
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: steevi
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: read environment file
        run: cat .env >>${GITHUB_ENV}          
      
      - name: Check Var
        run: echo ${{ env.caddy_version}}

      # - name: Build container image
      #   run:  source source.rc && docker build --build-arg VERSION=${CADDY_VERSION} -t steevi/caddy-cloudflare:${GITHUB_SHA} .

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'steevi/caddy-cloudflare:${{ github.sha }}'
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   if: always()
      #   with:
      #     sarif_file: 'trivy-results.sarif'

      # - name: Build and push container image
      #   run:  source source.rc && docker build --build-arg VERSION=${CADDY_VERSION} -t steevi/caddy-cloudflare:${CADDY_VERSION} . && docker push steevi/caddy-cloudflare:${CADDY_VERSION}