
  
name: 'Build on Master'

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest 
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: steevi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build container image
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ghcr.io/xnaas/caddy:latest